# Generated by Django 4.2 on 2023-04-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(max_length=255, upload_to='images/%Y/%m/%d/'),
        ),
    ]
