# Generated by Django 4.2 on 2023-04-25 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60, verbose_name='Номер телефона')),
                ('type', models.CharField(choices=[('PRODUCER', 'Producer'), ('CONSUMER', 'Consumer')], default='CONSUMER', max_length=10, verbose_name='Тип пользователя')),
                ('geo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Геолокация')),
                ('rating', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Рейтинг')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
